# Generated by Django 5.0.14 on 2026-06-02 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_consultation_consult_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationChat',
            fields=[
                ('chat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor')], max_length=20)),
                ('sender_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('consultation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='doctor.consultation')),
            ],
            options={
                'db_table': 'consultation_chats',
                'ordering': ['sent_at'],
            },
        ),
    ]
