# Generated by Django 5.0.6 on 2026-06-30 14:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_existing_slots(apps, schema_editor):
    DoctorSlot = apps.get_model('doctor', 'DoctorSlot')
    for slot in DoctorSlot.objects.select_related('doctor_id').all().iterator():
        update_fields = []
        doctor = getattr(slot, 'doctor_id', None)
        if doctor and not slot.hospital_id:
            slot.hospital_id = doctor.hospital_id_id
            update_fields.append('hospital')
        if doctor and not slot.consultation_fee:
            slot.consultation_fee = doctor.consultation_fee or 0
            update_fields.append('consultation_fee')
        if slot.is_booked and slot.status != 'booked':
            slot.status = 'booked'
            update_fields.append('status')
        elif slot.is_blocked and slot.status != 'blocked':
            slot.status = 'blocked'
            update_fields.append('status')
        if update_fields:
            slot.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_consultationchat'),
        ('hospital', '0010_department_department_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorslot',
            name='block_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorslot',
            name='blocked_by',
            field=models.CharField(blank=True, choices=[('hospital_admin', 'Hospital Admin'), ('doctor', 'Doctor')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctorslot',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='doctorslot',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_slots', to='hospital.hospitalregistration'),
        ),
        migrations.AddField(
            model_name='doctorslot',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked')], default='available', max_length=15),
        ),
        migrations.AddField(
            model_name='doctorslot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('schedule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('working_days', models.JSONField(default=list)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.PositiveIntegerField()),
                ('consultation_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both')], default='both', max_length=10)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctor.doctorregistration')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedules', to='hospital.hospitalregistration')),
            ],
            options={
                'db_table': 'doctor_schedules',
                'ordering': ['doctor__full_name', 'start_time'],
            },
        ),
        migrations.AlterField(
            model_name='doctorslot',
            name='consult_type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both'), ('in_person', 'In Person (Legacy)')], default='online', max_length=10),
        ),
        migrations.AddField(
            model_name='doctorslot',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='doctor.doctorschedule'),
        ),
        migrations.RunPython(backfill_existing_slots, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='doctorslot',
            index=models.Index(fields=['doctor_id', 'slot_date', 'start_time', 'end_time'], name='doctor_slot_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorslot',
            index=models.Index(fields=['hospital', 'slot_date', 'status'], name='doctor_slot_board_idx'),
        ),
    ]
