# Generated by Django 5.0.6 on 2026-07-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctorslot_block_reason_doctorslot_blocked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='payment_hold_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
