# Generated by Django 5.0.14 on 2026-06-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federated', '0004_epidemictrend_is_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epidemictrend',
            name='is_auto_detected',
            field=models.BooleanField(default=False),
        ),
    ]
