# Generated by Django 4.2 on 2026-06-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincredentials',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15),
        ),
    ]
