# Generated by Django 4.2 on 2026-06-02 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_logincredentials_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('developer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g. Full Stack Developer', max_length=100)),
                ('department', models.CharField(blank=True, help_text='e.g. MCA Final Year', max_length=100, null=True)),
                ('college', models.CharField(default='MIIT', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='developers/')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'developers',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('feature_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='features/')),
                ('icon', models.CharField(blank=True, help_text='Emoji icon e.g. 🧠', max_length=10, null=True)),
                ('category', models.CharField(blank=True, help_text='e.g. AI, Emergency, Lab', max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_features',
                'ordering': ['order', 'title'],
            },
        ),
    ]
