# Generated by Django 4.2 on 2026-06-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_developer_projectfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincredentials',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text='Force user to change password on next login'),
        ),
        migrations.AddField(
            model_name='logincredentials',
            name='temp_password',
            field=models.CharField(blank=True, help_text='Temporary password (cleared after the user sets their own)', max_length=100, null=True),
        ),
    ]
