# Generated by Django 5.0.14 on 2026-06-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_bed_emergency_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='emergency_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='minimum_lock_days',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='hospitalinventory',
            name='condition',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('needs_repair', 'Needs Repair'), ('out_of_service', 'Out of Service')], default='good', max_length=20),
        ),
    ]
