# Generated by Django 5.0.14 on 2026-06-03 17:23

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_developer_projectfeature'),
        ('hospital', '0007_bed_emergency_locked_at_bed_minimum_lock_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentStockMovement',
            fields=[
                ('movement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(choices=[('purchase', 'New Purchase'), ('transfer_in', 'Transfer In'), ('donation', 'Donation'), ('repair_return', 'Returned from Repair'), ('used', 'Used/Consumed'), ('damaged', 'Damaged'), ('repair_out', 'Sent for Repair'), ('disposed', 'Disposed/Expired'), ('transfer_out', 'Transferred Out'), ('lost', 'Lost/Missing')], max_length=50)),
                ('vendor_name', models.CharField(blank=True, help_text='For purchase movements', max_length=200, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('stock_before', models.IntegerField(help_text='Stock count before movement')),
                ('stock_after', models.IntegerField(help_text='Stock count after movement')),
                ('movement_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='hospital.hospitalinventory')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='auth_app.logincredentials')),
            ],
            options={
                'db_table': 'equipment_stock_movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
