# Generated by Django 4.2 on 2026-06-04 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_equipmentstockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalpatient',
            name='medications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hospitalpatient',
            name='source',
            field=models.CharField(choices=[('manual', 'Manually Added'), ('import', 'CSV Import'), ('demo', 'Demo Generated')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalpatient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalpatient',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hospitalpatient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hospitalpatient',
            name='visit_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
