# Generated by Django 4.2 on 2026-06-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_hospitalpatient_medications_hospitalpatient_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_photo',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
