# Generated by Django 4.2 on 2026-06-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0007_ambulancedispatch_bed_ready_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('driver', 'Driver'), ('admin', 'Admin'), ('system', 'System')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='driver_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='driver_report_type',
            field=models.CharField(blank=True, choices=[('patient_not_found', 'Patient Not Found'), ('patient_left', 'Patient Already Left'), ('fake_emergency', 'Fake Emergency'), ('wrong_location', 'Wrong Location'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='false_alarm_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='patient_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ambulancedispatch',
            name='dispatch_status',
            field=models.CharField(choices=[('dispatched', 'Dispatched'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('pending_acknowledgment', 'Pending Acknowledgment'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='dispatched', max_length=25),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('no_drivers', 'No Drivers Available'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
    ]
