# Generated by Django 5.0.14 on 2026-06-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_alter_ehrimage_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehrimage',
            name='image_type',
            field=models.CharField(choices=[('xray', 'X-Ray'), ('mri', 'MRI Scan'), ('skin', 'Skin Photo'), ('ct_scan', 'CT Scan'), ('ultrasound', 'Ultrasound'), ('lab_report', 'Lab Report'), ('other', 'Other')], max_length=20),
        ),
    ]
