# Generated by Django 5.0.14 on 2026-06-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_alter_ehrimage_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestorder',
            name='no_show_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestorder',
            name='no_show_marked_by',
            field=models.CharField(blank=True, default='', help_text="'auto' or 'lab_tech'", max_length=20),
        ),
        migrations.AddField(
            model_name='labtestorder',
            name='reminder_30min_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='labtestorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20),
        ),
    ]
