# Generated by Django 5.0.14 on 2026-06-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_pharmacyinventory_reserved_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorder',
            name='reservation_expires_at',
            field=models.DateTimeField(blank=True, help_text='Auto-release deadline (10 min after reserved_at; unset for Rx orders)', null=True),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='reserved_at',
            field=models.DateTimeField(blank=True, help_text='When stock was reserved', null=True),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='stock_reserved',
            field=models.BooleanField(default=False, help_text='Stock held pending payment'),
        ),
    ]
