# Generated by Django 5.0.14 on 2026-06-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_medicineorder_reservation_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorder',
            name='delivery_phone',
            field=models.CharField(blank=True, help_text='Contact number for delivery', max_length=15),
        ),
    ]
