# Generated by Django 5.0.14 on 2026-06-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_medicineorder_delivery_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorder',
            name='driver_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='issue_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='issue_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='medicineorder',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('prescription_required', 'Prescription Required'), ('awaiting_prescription', 'Awaiting Prescription'), ('prescription_uploaded', 'Prescription Uploaded'), ('prescription_approved', 'Prescription Approved'), ('verified', 'Verified'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('wrong_product', 'Wrong Product Reported'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
