# Generated by Django 5.0.14 on 2026-06-09 15:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_medicineorder_driver_name_medicineorder_driver_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorder',
            name='final_resolution',
            field=models.CharField(blank=True, choices=[('refunded', 'Refunded'), ('redelivered', 'Redelivered')], max_length=20),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='patient_desired_resolution',
            field=models.CharField(blank=True, choices=[('refund', 'Refund'), ('redeliver', 'Redeliver')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medicineorder',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('prescription_required', 'Prescription Required'), ('awaiting_prescription', 'Awaiting Prescription'), ('prescription_uploaded', 'Prescription Uploaded'), ('prescription_approved', 'Prescription Approved'), ('verified', 'Verified'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('wrong_product', 'Wrong Product Reported'), ('resolved', 'Resolved'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='medicineorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='PharmacyDriver',
            fields=[
                ('driver_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='pharmacy.pharmacistregistration')),
            ],
            options={
                'db_table': 'pharmacy_drivers',
            },
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='pharmacy.pharmacydriver'),
        ),
    ]
