from django.urls import path
from .views import (
    HospitalDashboardView,
    AddDoctorView,
    AddLabTechView,
    AddDriverView,
    ListDoctorsView,
    UpdateDoctorView,
    UpdateLabTechView,
    UpdateDriverView,
    DeleteStaffView,
    StaffActionView,
    ListLabTechsView,
    ListDriversView,
    ListBedsView,
    AddBedView,
    UpdateBedView,
    UnlockEmergencyBedView,
    AvailableBedsView,
    ListInventoryView,
    AddInventoryItemView,
    UpdateInventoryView,
    EquipmentStockMovementView,
    ListDepartmentsView,
    AddDepartmentView,
    UpdateDepartmentView,
    ListHospitalEquipmentOrdersView,
    ConfirmDeliveryView,
    TrackOrderView,
    AddHospitalPatientView,
    ListHospitalPatientsView,
    GetHospitalPatientView,
    ExportTrainingDataView,
    HospitalPatientStatsView,
    ImportPatientsCSVView,
    ParseCSVHeadersView,
    ImportMappedCSVView,
    DownloadCSVTemplateView,
    GenerateDemoPatientsView,
    UploadImageView,
    InventoryImageUploadView,
    FileVendorComplaintView,
    DoctorScheduleView,
    HospitalLabConfigView,
)

urlpatterns = [
    path('dashboard/', HospitalDashboardView.as_view()),
    path('add-doctor/', AddDoctorView.as_view()),
    path('add-lab-tech/', AddLabTechView.as_view()),
    path('add-driver/', AddDriverView.as_view()),
    path('doctors/', ListDoctorsView.as_view()),
    path('doctors/<uuid:doctor_id>/', UpdateDoctorView.as_view()),
    path('lab-techs/', ListLabTechsView.as_view()),
    path('lab-techs/<uuid:lab_tech_id>/', UpdateLabTechView.as_view()),
    path('drivers/', ListDriversView.as_view()),
    path('drivers/<uuid:driver_id>/', UpdateDriverView.as_view()),
    path('staff/<str:role>/<uuid:staff_id>/delete/', DeleteStaffView.as_view()),
    path('staff/<str:role>/<uuid:staff_id>/action/', StaffActionView.as_view()),
    path('beds/', ListBedsView.as_view()),
    path('beds/add/', AddBedView.as_view()),
    path('beds/available/', AvailableBedsView.as_view()),
    path('beds/<uuid:bed_id>/unlock/', UnlockEmergencyBedView.as_view()),
    path('beds/<uuid:bed_id>/', UpdateBedView.as_view()),
    path('inventory/', ListInventoryView.as_view()),
    path('inventory/add/', AddInventoryItemView.as_view()),
    path('equipment/<uuid:equipment_id>/stock/', EquipmentStockMovementView.as_view()),
    path('inventory/<uuid:item_id>/upload-image/', InventoryImageUploadView.as_view()),
    path('inventory/<uuid:inventory_id>/', UpdateInventoryView.as_view()),
    path('file-vendor-complaint/', FileVendorComplaintView.as_view()),
    path('departments/', ListDepartmentsView.as_view()),
    path('departments/add/', AddDepartmentView.as_view()),
    path('departments/<uuid:dept_id>/', UpdateDepartmentView.as_view()),
    path('equipment-orders/', ListHospitalEquipmentOrdersView.as_view()),
    path('orders/<uuid:order_id>/confirm-delivery/', ConfirmDeliveryView.as_view()),
    path('orders/<uuid:order_id>/track/', TrackOrderView.as_view()),
    path('patients/', ListHospitalPatientsView.as_view()),
    path('patients/add/', AddHospitalPatientView.as_view()),
    path('patients/stats/', HospitalPatientStatsView.as_view()),
    path('patients/export/', ExportTrainingDataView.as_view()),
    path('patients/import-csv/', ImportPatientsCSVView.as_view()),
    path('patients/parse-csv/', ParseCSVHeadersView.as_view()),
    path('patients/import-mapped/', ImportMappedCSVView.as_view()),
    path('patients/csv-template/', DownloadCSVTemplateView.as_view()),
    path('patients/generate-demo/', GenerateDemoPatientsView.as_view()),
    path('patients/<uuid:patient_id>/', GetHospitalPatientView.as_view()),
    path('upload-image/', UploadImageView.as_view()),
    path('doctor-schedule/', DoctorScheduleView.as_view()),
    path('lab-config/', HospitalLabConfigView.as_view()),
]
